@php
    use App\Http\Controllers\dataController;
    use App\Http\Controllers\langController;
    use App\Http\Controllers\settingsController;
    use Illuminate\Support\Facades\Cache;

    $settings       = (new settingsController())->get();
    $lang           = new langController();
    $dataController = new dataController();

    $get   = DB::table('containers_sky')->where('id', $id)->first();
    $data_ = DB::table('store_out_sky')->where('container_id', $id)->get();

    $clients = Cache::remember('clients_compant_accounting', env('CACHE'), function () {
        return DB::table('clients')->select('id', 'name', 'code')->get()->keyBy('id');
    });

    $isRtl  = (auth()->user()->lang ?? 'en') === 'ar';
    $cellTh = 'background: #fafbfc; color: #5b667a; font-size: 10px; text-transform: uppercase; letter-spacing: 0.6px; padding: 6px 8px; border: 1px solid #e2e6ee; text-align: '.($isRtl ? 'right' : 'left').';';
    $cellTd = 'padding: 6px 8px; border: 1px solid #e2e6ee; font-size: 12px;';
@endphp

<input type="hidden" data-name="title" class="client_data" value="{{ $get->number }}-packing">

<div style="padding: 18px; direction: {{ $isRtl ? 'rtl' : 'ltr' }}; color: #1a2233; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 12px;">

    @include('partials.print_header', [
        'settings' => $settings,
        'lang'     => $lang,
        'title'    => $lang->write('Packing list') . ' — ' . $get->name,
        'subtitle' => '#' . $get->number,
    ])

    {{-- Trip summary --}}
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 16px;">
        <thead>
            <tr>
                <th style="{{ $cellTh }}">{{ $lang->write('Trip name') }}</th>
                <th style="{{ $cellTh }}">{{ $lang->write('Trip number') }}</th>
                <th style="{{ $cellTh }}">{{ $lang->write('Port of Arrival') }}</th>
                <th style="{{ $cellTh }}">{{ $lang->write('Created at') }}</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="{{ $cellTd }}">{{ $get->name }}</td>
                <td style="{{ $cellTd }}">{{ $get->number }}</td>
                <td style="{{ $cellTd }}">{{ $get->arrival }}</td>
                <td style="{{ $cellTd }}">{{ $get->created_date }} {{ $get->created_time }}</td>
            </tr>
        </tbody>
    </table>

    {{-- Packing list — minimal, recipient-facing --}}
    <table style="width: 100%; border-collapse: collapse;">
        <thead>
            <tr>
                <th style="{{ $cellTh }}">{{ $lang->write('Client code') }}</th>
                <th style="{{ $cellTh }}">{{ $lang->write('Type') }}</th>
                <th style="{{ $cellTh }}">{{ $lang->write('Category') }}</th>
                <th style="{{ $cellTh }} text-align: right;">{{ $lang->write('Pieces') }}</th>
                <th style="{{ $cellTh }} text-align: right;">{{ $lang->write('KG') }}</th>
                <th style="{{ $cellTh }} text-align: right;">{{ $lang->write('CBM') }}</th>
                <th style="{{ $cellTh }}">{{ $lang->write('Notes') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($data_ as $item)
                @php $data = DB::table('store_sky')->where('id', $item->in_id)->first(); @endphp
                <tr>
                    <td style="{{ $cellTd }} font-weight: 600;">{{ $clients[$item->client_id]->code ?? '-' }}</td>
                    <td style="{{ $cellTd }}">{{ $lang->write(ucfirst($data->type ?? '')) }}</td>
                    <td style="{{ $cellTd }}">{{ $data->category ?? '' }}</td>
                    <td style="{{ $cellTd }} text-align: right;">{{ $item->number }}</td>
                    <td style="{{ $cellTd }} text-align: right;">{{ $item->kg }}</td>
                    <td style="{{ $cellTd }} text-align: right;">{{ $item->cbm }}</td>
                    <td style="{{ $cellTd }}">{{ strlen($data->notes ?? '') > 0 ? $data->notes : '-' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div style="color: #5b667a; font-size: 9px; text-align: center; margin-top: 14px;">
        {{ $lang->write('Generated by') }} {{ $settings['company_name'] ?? '' }} · {{ date('Y-m-d H:i') }}
    </div>
</div>
