
CREATE TABLE `accounting_periods` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `period_year` smallint NOT NULL,
  `period_month` tinyint NOT NULL,
  `period_start` date NOT NULL,
  `period_end` date NOT NULL,
  `status` enum('open','closed') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open',
  `closed_by_user_id` bigint unsigned DEFAULT NULL,
  `closed_by_user_name` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `closed_at` timestamp NULL DEFAULT NULL,
  `reopened_by_user_id` bigint unsigned DEFAULT NULL,
  `reopened_by_user_name` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reopened_at` timestamp NULL DEFAULT NULL,
  `notes` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `accounting_periods_period_year_period_month_unique` (`period_year`,`period_month`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `audit_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned DEFAULT NULL,
  `user_type` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `branch_id` bigint unsigned DEFAULT NULL,
  `action` varchar(48) COLLATE utf8mb4_unicode_ci NOT NULL,
  `target_table` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `target_id` bigint unsigned DEFAULT NULL,
  `payload` json DEFAULT NULL,
  `ip` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `context` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `audit_log_target_table_target_id_index` (`target_table`,`target_id`),
  KEY `audit_log_user_id_created_at_index` (`user_id`,`created_at`),
  KEY `audit_log_action_created_at_index` (`action`,`created_at`),
  KEY `audit_log_created_at_index` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=257 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `branch_staff` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `branch_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `role` enum('MANAGER','RECEIVER','COURIER','AUDITOR') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'RECEIVER',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `branch_staff_branch_user_unique` (`branch_id`,`user_id`),
  KEY `branch_staff_user_id_is_active_index` (`user_id`,`is_active`),
  CONSTRAINT `branch_staff_branch_id_foreign` FOREIGN KEY (`branch_id`) REFERENCES `tracking_branches` (`id`) ON DELETE CASCADE,
  CONSTRAINT `branch_staff_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=573 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `branches` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` text COLLATE utf8mb4_general_ci,
  `name_en` text COLLATE utf8mb4_general_ci,
  `name_zh` text COLLATE utf8mb4_general_ci,
  `balance_usd` text COLLATE utf8mb4_general_ci,
  `balance_cny` text COLLATE utf8mb4_general_ci,
  `balance_den` text COLLATE utf8mb4_general_ci,
  `balance_eur` text COLLATE utf8mb4_general_ci,
  `deleted` text COLLATE utf8mb4_general_ci,
  `created_date` date DEFAULT NULL,
  `created_time` text COLLATE utf8mb4_general_ci,
  `created_by` text COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `branches_transactions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `type` text COLLATE utf8mb4_general_ci,
  `data` text COLLATE utf8mb4_general_ci,
  `created_date` date DEFAULT NULL,
  `created_time` text COLLATE utf8mb4_general_ci,
  `created_by` text COLLATE utf8mb4_general_ci,
  `value` text COLLATE utf8mb4_general_ci,
  `transfer_value` text COLLATE utf8mb4_general_ci,
  `currency` text COLLATE utf8mb4_general_ci,
  `to_currency` text COLLATE utf8mb4_general_ci,
  `plus_minus` text COLLATE utf8mb4_general_ci,
  `branch` text COLLATE utf8mb4_general_ci,
  `notes` text COLLATE utf8mb4_general_ci,
  `purpose` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `owner_id` bigint unsigned DEFAULT NULL,
  `auto_id` text COLLATE utf8mb4_general_ci,
  `transaction_number` text COLLATE utf8mb4_general_ci,
  `exchange_rate` text COLLATE utf8mb4_general_ci,
  `usd_value` text COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`),
  KEY `branches_transactions_owner_id_index` (`owner_id`)
) ENGINE=InnoDB AUTO_INCREMENT=95 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `buyer_accounts` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `buyer_id` bigint unsigned NOT NULL,
  `balance` decimal(14,2) NOT NULL DEFAULT '0.00',
  `reserved_balance` decimal(14,2) NOT NULL DEFAULT '0.00',
  `total_spent` decimal(14,2) NOT NULL DEFAULT '0.00',
  `total_received` decimal(14,2) NOT NULL DEFAULT '0.00',
  `min_threshold` decimal(14,2) NOT NULL DEFAULT '1000.00',
  `last_reconciled_at` timestamp NULL DEFAULT NULL,
  `last_reconciled_by` bigint unsigned DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `buyer_accounts_buyer_id_unique` (`buyer_id`),
  KEY `buyer_accounts_last_reconciled_by_foreign` (`last_reconciled_by`),
  CONSTRAINT `buyer_accounts_buyer_id_foreign` FOREIGN KEY (`buyer_id`) REFERENCES `buyers` (`id`) ON DELETE CASCADE,
  CONSTRAINT `buyer_accounts_last_reconciled_by_foreign` FOREIGN KEY (`last_reconciled_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `buyer_reconciliations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `buyer_account_id` bigint unsigned NOT NULL,
  `period_start` date NOT NULL,
  `period_end` date NOT NULL,
  `system_balance` decimal(14,2) NOT NULL,
  `actual_balance` decimal(14,2) NOT NULL,
  `difference` decimal(14,2) NOT NULL,
  `difference_reason` text COLLATE utf8mb4_unicode_ci,
  `adjustment_tx_id` bigint unsigned DEFAULT NULL,
  `attachment_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reconciled_by_id` bigint unsigned NOT NULL,
  `approved_by_id` bigint unsigned DEFAULT NULL,
  `status` enum('PENDING_APPROVAL','APPROVED','REJECTED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING_APPROVAL',
  `notes` text COLLATE utf8mb4_unicode_ci,
  `rejection_reason` text COLLATE utf8mb4_unicode_ci,
  `reconciled_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `approved_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `buyer_reconciliations_adjustment_tx_id_foreign` (`adjustment_tx_id`),
  KEY `buyer_reconciliations_reconciled_by_id_foreign` (`reconciled_by_id`),
  KEY `buyer_reconciliations_approved_by_id_foreign` (`approved_by_id`),
  KEY `buyer_reconciliations_buyer_account_id_period_end_index` (`buyer_account_id`,`period_end`),
  KEY `buyer_reconciliations_status_index` (`status`),
  CONSTRAINT `buyer_reconciliations_adjustment_tx_id_foreign` FOREIGN KEY (`adjustment_tx_id`) REFERENCES `buyer_transactions` (`id`) ON DELETE SET NULL,
  CONSTRAINT `buyer_reconciliations_approved_by_id_foreign` FOREIGN KEY (`approved_by_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `buyer_reconciliations_buyer_account_id_foreign` FOREIGN KEY (`buyer_account_id`) REFERENCES `buyer_accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `buyer_reconciliations_reconciled_by_id_foreign` FOREIGN KEY (`reconciled_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `buyer_transactions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `buyer_account_id` bigint unsigned NOT NULL,
  `buyer_id` bigint unsigned NOT NULL,
  `type` enum('INITIAL_DEPOSIT','TOP_UP','PURCHASE','PURCHASE_REFUND','RECONCILIATION_ADJUSTMENT','TRANSFER_IN','TRANSFER_OUT','WITHDRAWAL') COLLATE utf8mb4_unicode_ci NOT NULL,
  `amount` decimal(14,2) NOT NULL,
  `balance_before` decimal(14,2) NOT NULL,
  `balance_after` decimal(14,2) NOT NULL,
  `local_amount` decimal(14,2) DEFAULT NULL,
  `local_currency` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `exchange_rate` decimal(18,8) DEFAULT NULL,
  `exchange_rate_id` bigint unsigned DEFAULT NULL,
  `purchase_order_id` bigint unsigned DEFAULT NULL,
  `invoice_image_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `receipt_image_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `proof_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `performed_by_id` bigint unsigned NOT NULL,
  `approved_by_id` bigint unsigned DEFAULT NULL,
  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `transaction_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `buyer_transactions_buyer_id_foreign` (`buyer_id`),
  KEY `buyer_transactions_exchange_rate_id_foreign` (`exchange_rate_id`),
  KEY `buyer_transactions_performed_by_id_foreign` (`performed_by_id`),
  KEY `buyer_transactions_approved_by_id_foreign` (`approved_by_id`),
  KEY `buyer_transactions_buyer_account_id_transaction_date_index` (`buyer_account_id`,`transaction_date`),
  KEY `buyer_transactions_type_transaction_date_index` (`type`,`transaction_date`),
  KEY `buyer_transactions_purchase_order_id_index` (`purchase_order_id`),
  CONSTRAINT `buyer_transactions_approved_by_id_foreign` FOREIGN KEY (`approved_by_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `buyer_transactions_buyer_account_id_foreign` FOREIGN KEY (`buyer_account_id`) REFERENCES `buyer_accounts` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `buyer_transactions_buyer_id_foreign` FOREIGN KEY (`buyer_id`) REFERENCES `buyers` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `buyer_transactions_exchange_rate_id_foreign` FOREIGN KEY (`exchange_rate_id`) REFERENCES `exchange_rates` (`id`) ON DELETE SET NULL,
  CONSTRAINT `buyer_transactions_performed_by_id_foreign` FOREIGN KEY (`performed_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `buyer_transactions_purchase_order_id_foreign` FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `buyers` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `code` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `full_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `primary_warehouse_id` bigint unsigned NOT NULL,
  `max_order_value` decimal(14,2) NOT NULL DEFAULT '5000.00',
  `can_approve_orders` tinyint(1) NOT NULL DEFAULT '0',
  `status` enum('ACTIVE','SUSPENDED','TERMINATED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE',
  `hired_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `buyers_user_id_unique` (`user_id`),
  UNIQUE KEY `buyers_code_unique` (`code`),
  KEY `buyers_primary_warehouse_id_status_index` (`primary_warehouse_id`,`status`),
  CONSTRAINT `buyers_primary_warehouse_id_foreign` FOREIGN KEY (`primary_warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `buyers_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `cache` (
  `key` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `value` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `expiration` int NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `cache_locks` (
  `key` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `owner` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `expiration` int NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `cash_counts` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `branch_id` bigint unsigned NOT NULL,
  `currency` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `system_balance` decimal(18,4) NOT NULL,
  `counted_amount` decimal(18,4) NOT NULL,
  `variance` decimal(18,4) NOT NULL,
  `count_date` date NOT NULL,
  `counted_by_user_id` bigint unsigned DEFAULT NULL,
  `counted_by_user_name` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `counted_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `notes` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `adjustment_posted` tinyint(1) NOT NULL DEFAULT '0',
  `adjustment_transaction_id` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `cash_counts_branch_id_index` (`branch_id`),
  KEY `cash_counts_count_date_index` (`count_date`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `chart_of_accounts` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name_en` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name_zh` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type` enum('asset','liability','equity','revenue','expense') COLLATE utf8mb4_unicode_ci NOT NULL,
  `normal_balance` enum('debit','credit') COLLATE utf8mb4_unicode_ci NOT NULL,
  `parent_id` bigint unsigned DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `is_system` tinyint(1) NOT NULL DEFAULT '0',
  `derivation_key` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `chart_of_accounts_code_unique` (`code`),
  KEY `chart_of_accounts_parent_id_index` (`parent_id`),
  KEY `chart_of_accounts_derivation_key_index` (`derivation_key`)
) ENGINE=InnoDB AUTO_INCREMENT=47 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `client_devices` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `client_id` bigint unsigned NOT NULL,
  `platform` enum('ios','android','web') COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL,
  `app_version` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `device_model` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `os_version` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_seen_at` timestamp NULL DEFAULT NULL,
  `revoked_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `clients` (
  `id` int NOT NULL AUTO_INCREMENT,
  `code` text COLLATE utf8mb4_general_ci,
  `name` text COLLATE utf8mb4_general_ci,
  `email` text COLLATE utf8mb4_general_ci,
  `phone` text COLLATE utf8mb4_general_ci,
  `country` text COLLATE utf8mb4_general_ci,
  `branch` text COLLATE utf8mb4_general_ci,
  `branch_txt` text COLLATE utf8mb4_general_ci,
  `type` text COLLATE utf8mb4_general_ci,
  `balance_usd` text COLLATE utf8mb4_general_ci,
  `balance_eur` text COLLATE utf8mb4_general_ci,
  `balance_den` text COLLATE utf8mb4_general_ci,
  `balance_cny` text COLLATE utf8mb4_general_ci,
  `created_date` date DEFAULT NULL,
  `created_time` text COLLATE utf8mb4_general_ci,
  `created_by` text COLLATE utf8mb4_general_ci,
  `password` text COLLATE utf8mb4_general_ci,
  `remember_token` text COLLATE utf8mb4_general_ci,
  `deleted` text COLLATE utf8mb4_general_ci,
  `not_active` text COLLATE utf8mb4_general_ci,
  `lang` text COLLATE utf8mb4_general_ci,
  `notify_transactions` tinyint(1) NOT NULL DEFAULT '1',
  `notify_shipments` tinyint(1) NOT NULL DEFAULT '1',
  `notify_receipts` tinyint(1) NOT NULL DEFAULT '1',
  `portal_token` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `portal_token_issued_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `clients_portal_token_unique` (`portal_token`)
) ENGINE=InnoDB AUTO_INCREMENT=422 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `clients_transactions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` text COLLATE utf8mb4_general_ci,
  `type` text COLLATE utf8mb4_general_ci,
  `data` text COLLATE utf8mb4_general_ci,
  `created_date` date DEFAULT NULL,
  `created_time` text COLLATE utf8mb4_general_ci,
  `created_by` text COLLATE utf8mb4_general_ci,
  `value` text COLLATE utf8mb4_general_ci,
  `transfer_value` text COLLATE utf8mb4_general_ci,
  `currency` text COLLATE utf8mb4_general_ci,
  `to_currency` text COLLATE utf8mb4_general_ci,
  `plus_minus` text COLLATE utf8mb4_general_ci,
  `branch` text COLLATE utf8mb4_general_ci,
  `notes` text COLLATE utf8mb4_general_ci,
  `purpose` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `calc` varchar(8) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `auto_id` text COLLATE utf8mb4_general_ci,
  `transaction_number` text COLLATE utf8mb4_general_ci,
  `commission` text COLLATE utf8mb4_general_ci,
  `commission_reason` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `remaining_balance` text COLLATE utf8mb4_general_ci,
  `exchange_rate` text COLLATE utf8mb4_general_ci,
  `usd_value` text COLLATE utf8mb4_general_ci,
  `status` text COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`),
  KEY `clients_transactions_calc_index` (`calc`)
) ENGINE=InnoDB AUTO_INCREMENT=1020 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `containers_sea` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` text COLLATE utf8mb4_general_ci,
  `supplier` text COLLATE utf8mb4_general_ci,
  `payment_supplier` text COLLATE utf8mb4_general_ci,
  `cost` text COLLATE utf8mb4_general_ci,
  `profit` text COLLATE utf8mb4_general_ci,
  `commission` text COLLATE utf8mb4_general_ci,
  `custom_container_payment` text COLLATE utf8mb4_general_ci,
  `branch` text COLLATE utf8mb4_general_ci,
  `ship_from` text COLLATE utf8mb4_general_ci,
  `client_price` text COLLATE utf8mb4_general_ci,
  `type` text COLLATE utf8mb4_general_ci,
  `name` text COLLATE utf8mb4_general_ci,
  `number` text COLLATE utf8mb4_general_ci,
  `costs` text COLLATE utf8mb4_general_ci,
  `data` text COLLATE utf8mb4_general_ci,
  `size` text COLLATE utf8mb4_general_ci,
  `arrival` text COLLATE utf8mb4_general_ci,
  `packaging_type` text COLLATE utf8mb4_general_ci,
  `fees` text COLLATE utf8mb4_general_ci,
  `status` text COLLATE utf8mb4_general_ci,
  `created_date` date DEFAULT NULL,
  `created_time` text COLLATE utf8mb4_general_ci,
  `created_by` text COLLATE utf8mb4_general_ci,
  `canceled` text COLLATE utf8mb4_general_ci,
  `canceled_by` text COLLATE utf8mb4_general_ci,
  `canceled_date` date DEFAULT NULL,
  `canceled_time` text COLLATE utf8mb4_general_ci,
  `notes` text COLLATE utf8mb4_general_ci,
  `link` text COLLATE utf8mb4_general_ci,
  `custom_status` text COLLATE utf8mb4_general_ci,
  `pay_branch_client` text COLLATE utf8mb4_general_ci,
  `pay_branch_supplier` text COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=526 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `containers_sea_fees` (
  `id` int NOT NULL AUTO_INCREMENT,
  `container_id` text COLLATE utf8mb4_general_ci,
  `container_number` text COLLATE utf8mb4_general_ci,
  `purpose` text COLLATE utf8mb4_general_ci,
  `type` text COLLATE utf8mb4_general_ci,
  `branch` text COLLATE utf8mb4_general_ci,
  `value` text COLLATE utf8mb4_general_ci,
  `currency` text COLLATE utf8mb4_general_ci,
  `exchange_rate` text COLLATE utf8mb4_general_ci,
  `result_usd` text COLLATE utf8mb4_general_ci,
  `notes` text COLLATE utf8mb4_general_ci,
  `created_date` date DEFAULT NULL,
  `created_time` text COLLATE utf8mb4_general_ci,
  `created_by` text COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `containers_sky` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` text COLLATE utf8mb4_general_ci,
  `supplier` text COLLATE utf8mb4_general_ci,
  `payment_supplier` text COLLATE utf8mb4_general_ci,
  `cost` text COLLATE utf8mb4_general_ci,
  `profit` text COLLATE utf8mb4_general_ci,
  `commission` text COLLATE utf8mb4_general_ci,
  `custom_container_payment` text COLLATE utf8mb4_general_ci,
  `branch` text COLLATE utf8mb4_general_ci,
  `ship_from` text COLLATE utf8mb4_general_ci,
  `client_price` text COLLATE utf8mb4_general_ci,
  `type` text COLLATE utf8mb4_general_ci,
  `name` text COLLATE utf8mb4_general_ci,
  `number` text COLLATE utf8mb4_general_ci,
  `costs` text COLLATE utf8mb4_general_ci,
  `data` text COLLATE utf8mb4_general_ci,
  `size` text COLLATE utf8mb4_general_ci,
  `arrival` text COLLATE utf8mb4_general_ci,
  `packaging_type` text COLLATE utf8mb4_general_ci,
  `fees` text COLLATE utf8mb4_general_ci,
  `status` text COLLATE utf8mb4_general_ci,
  `created_date` date DEFAULT NULL,
  `created_time` text COLLATE utf8mb4_general_ci,
  `created_by` text COLLATE utf8mb4_general_ci,
  `canceled` text COLLATE utf8mb4_general_ci,
  `canceled_by` text COLLATE utf8mb4_general_ci,
  `canceled_date` date DEFAULT NULL,
  `canceled_time` text COLLATE utf8mb4_general_ci,
  `notes` text COLLATE utf8mb4_general_ci,
  `link` text COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `containers_sky_fees` (
  `id` int NOT NULL AUTO_INCREMENT,
  `container_id` text COLLATE utf8mb4_general_ci,
  `container_number` text COLLATE utf8mb4_general_ci,
  `purpose` text COLLATE utf8mb4_general_ci,
  `type` text COLLATE utf8mb4_general_ci,
  `branch` text COLLATE utf8mb4_general_ci,
  `value` text COLLATE utf8mb4_general_ci,
  `currency` text COLLATE utf8mb4_general_ci,
  `exchange_rate` text COLLATE utf8mb4_general_ci,
  `result_usd` text COLLATE utf8mb4_general_ci,
  `notes` text COLLATE utf8mb4_general_ci,
  `created_date` date DEFAULT NULL,
  `created_time` text COLLATE utf8mb4_general_ci,
  `created_by` text COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `custody_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `shipment_source_table` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `shipment_source_id` bigint unsigned NOT NULL,
  `shipment_piece_id` bigint unsigned DEFAULT NULL,
  `event_type` enum('RECEIVED_AT_HUB','DISPATCHED','RECEIVED_AT_BRANCH','READY_FOR_PICKUP','DELIVERED_TO_CUSTOMER','RETURNED_TO_HUB','LOST','DAMAGED') COLLATE utf8mb4_unicode_ci NOT NULL,
  `from_branch_id` bigint unsigned DEFAULT NULL,
  `to_branch_id` bigint unsigned DEFAULT NULL,
  `recorded_by_user_id` bigint unsigned NOT NULL,
  `occurred_at` timestamp NOT NULL,
  `photos` json DEFAULT NULL,
  `notes` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tracking_event_id` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `custody_events_shipment_piece_id_foreign` (`shipment_piece_id`),
  KEY `custody_events_from_branch_id_foreign` (`from_branch_id`),
  KEY `custody_events_recorded_by_user_id_foreign` (`recorded_by_user_id`),
  KEY `custody_events_tracking_event_id_foreign` (`tracking_event_id`),
  KEY `custody_events_shipment_occurred_idx` (`shipment_source_table`,`shipment_source_id`,`occurred_at`),
  KEY `custody_events_to_branch_id_event_type_index` (`to_branch_id`,`event_type`),
  CONSTRAINT `custody_events_from_branch_id_foreign` FOREIGN KEY (`from_branch_id`) REFERENCES `tracking_branches` (`id`) ON DELETE SET NULL,
  CONSTRAINT `custody_events_recorded_by_user_id_foreign` FOREIGN KEY (`recorded_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `custody_events_shipment_piece_id_foreign` FOREIGN KEY (`shipment_piece_id`) REFERENCES `shipment_pieces` (`id`) ON DELETE SET NULL,
  CONSTRAINT `custody_events_to_branch_id_foreign` FOREIGN KEY (`to_branch_id`) REFERENCES `tracking_branches` (`id`) ON DELETE SET NULL,
  CONSTRAINT `custody_events_tracking_event_id_foreign` FOREIGN KEY (`tracking_event_id`) REFERENCES `tracking_events` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=559 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `customs_brokers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` text COLLATE utf8mb4_general_ci,
  `type` text COLLATE utf8mb4_general_ci,
  `balance_usd` text COLLATE utf8mb4_general_ci,
  `balance_eur` text COLLATE utf8mb4_general_ci,
  `balance_cny` text COLLATE utf8mb4_general_ci,
  `balance_den` text COLLATE utf8mb4_general_ci,
  `created_date` date DEFAULT NULL,
  `created_time` text COLLATE utf8mb4_general_ci,
  `deleted` text COLLATE utf8mb4_general_ci,
  `created_by` text COLLATE utf8mb4_general_ci,
  `not_active` text COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `customs_brokers_transactions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `broker_id` text COLLATE utf8mb4_general_ci,
  `auto_id` text COLLATE utf8mb4_general_ci,
  `container_id` text COLLATE utf8mb4_general_ci,
  `container_number` text COLLATE utf8mb4_general_ci,
  `sky_sea` text COLLATE utf8mb4_general_ci,
  `pay_for` text COLLATE utf8mb4_general_ci,
  `branch` text COLLATE utf8mb4_general_ci,
  `value` text COLLATE utf8mb4_general_ci,
  `currency` text COLLATE utf8mb4_general_ci,
  `type` text COLLATE utf8mb4_general_ci,
  `from_value` text COLLATE utf8mb4_general_ci,
  `from_currency` text COLLATE utf8mb4_general_ci,
  `exchange_rate` text COLLATE utf8mb4_general_ci,
  `plus_minus` text COLLATE utf8mb4_general_ci,
  `created_date` date DEFAULT NULL,
  `created_time` text COLLATE utf8mb4_general_ci,
  `created_by` text COLLATE utf8mb4_general_ci,
  `transaction_number` text COLLATE utf8mb4_general_ci,
  `notes` text COLLATE utf8mb4_general_ci,
  `purpose` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `employee_action_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `branch_id` bigint unsigned DEFAULT NULL,
  `action` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `entity_type` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `entity_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payload` json DEFAULT NULL,
  `ip_address` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `employee_action_logs_user_id_created_at_index` (`user_id`,`created_at`),
  KEY `employee_action_logs_entity_type_entity_id_index` (`entity_type`,`entity_id`),
  KEY `employee_action_logs_branch_id_created_at_index` (`branch_id`,`created_at`),
  CONSTRAINT `employee_action_logs_branch_id_foreign` FOREIGN KEY (`branch_id`) REFERENCES `tracking_branches` (`id`) ON DELETE SET NULL,
  CONSTRAINT `employee_action_logs_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=499 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `employee_devices` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `platform` enum('ios','android','web') COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL,
  `app_version` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `device_model` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `os_version` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_seen_at` timestamp NULL DEFAULT NULL,
  `revoked_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `employee_devices_token_unique` (`token`),
  KEY `employee_devices_user_active_idx` (`user_id`,`revoked_at`),
  CONSTRAINT `employee_devices_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `exchange_rate_configs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `from_currency` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL,
  `to_currency` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL,
  `source` enum('API','MANUAL','HYBRID') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'API',
  `primary_provider` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'openexchangerates',
  `fallback_provider` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'frankfurter',
  `margin_type` enum('NONE','PERCENTAGE','FIXED_AMOUNT') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PERCENTAGE',
  `margin_value` decimal(8,4) NOT NULL DEFAULT '0.0000',
  `auto_update` tinyint(1) NOT NULL DEFAULT '1',
  `update_interval_hours` tinyint unsigned NOT NULL DEFAULT '6',
  `max_deviation_pct` decimal(5,2) DEFAULT '5.00',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `exchange_rate_configs_from_currency_to_currency_unique` (`from_currency`,`to_currency`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `exchange_rates` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `config_id` bigint unsigned NOT NULL,
  `from_currency` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL,
  `to_currency` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL,
  `raw_rate` decimal(18,8) NOT NULL,
  `raw_source` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `raw_fetched_at` timestamp NOT NULL,
  `margin_type` enum('NONE','PERCENTAGE','FIXED_AMOUNT') COLLATE utf8mb4_unicode_ci NOT NULL,
  `margin_value` decimal(8,4) NOT NULL,
  `margin_amount` decimal(18,8) NOT NULL,
  `effective_rate` decimal(18,8) NOT NULL,
  `is_manual_override` tinyint(1) NOT NULL DEFAULT '0',
  `override_by_id` bigint unsigned DEFAULT NULL,
  `override_reason` text COLLATE utf8mb4_unicode_ci,
  `status` enum('ACTIVE','SUPERSEDED','PENDING_APPROVAL','REJECTED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE',
  `valid_from` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `valid_until` timestamp NULL DEFAULT NULL,
  `requires_approval` tinyint(1) NOT NULL DEFAULT '0',
  `approved_by_id` bigint unsigned DEFAULT NULL,
  `approved_at` timestamp NULL DEFAULT NULL,
  `rejection_reason` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `exchange_rates_config_id_foreign` (`config_id`),
  KEY `exchange_rates_override_by_id_foreign` (`override_by_id`),
  KEY `exchange_rates_approved_by_id_foreign` (`approved_by_id`),
  KEY `exchange_rates_from_currency_to_currency_status_index` (`from_currency`,`to_currency`,`status`),
  KEY `exchange_rates_valid_from_index` (`valid_from`),
  CONSTRAINT `exchange_rates_approved_by_id_foreign` FOREIGN KEY (`approved_by_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `exchange_rates_config_id_foreign` FOREIGN KEY (`config_id`) REFERENCES `exchange_rate_configs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `exchange_rates_override_by_id_foreign` FOREIGN KEY (`override_by_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `failed_jobs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB AUTO_INCREMENT=49 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `fx_rate_history` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `currency` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rate` decimal(18,6) NOT NULL,
  `previous_rate` decimal(18,6) DEFAULT NULL,
  `set_by_user_id` bigint unsigned DEFAULT NULL,
  `set_by_user_name` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `effective_from` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `notes` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fx_rate_history_currency_index` (`currency`),
  KEY `fx_rate_history_set_by_user_id_index` (`set_by_user_id`),
  KEY `fx_rate_history_effective_from_index` (`effective_from`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `job_batches` (
  `id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `total_jobs` int NOT NULL,
  `pending_jobs` int NOT NULL,
  `failed_jobs` int NOT NULL,
  `failed_job_ids` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `options` mediumtext COLLATE utf8mb4_unicode_ci,
  `cancelled_at` int DEFAULT NULL,
  `created_at` int NOT NULL,
  `finished_at` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `jobs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `queue` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `attempts` tinyint unsigned NOT NULL,
  `reserved_at` int unsigned DEFAULT NULL,
  `available_at` int unsigned NOT NULL,
  `created_at` int unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `jobs_queue_index` (`queue`)
) ENGINE=InnoDB AUTO_INCREMENT=61 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `journal_entries` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `entry_date` date NOT NULL,
  `posted_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `posted_by_user_id` bigint unsigned DEFAULT NULL,
  `posted_by_user_name` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kind` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source_table` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source_id` bigint unsigned DEFAULT NULL,
  `transaction_number` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `branch_id` bigint unsigned DEFAULT NULL,
  `reverses_entry_id` bigint unsigned DEFAULT NULL,
  `reversed_by_entry_id` bigint unsigned DEFAULT NULL,
  `status` enum('open','reversed') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `journal_entries_entry_date_index` (`entry_date`),
  KEY `journal_entries_posted_at_index` (`posted_at`),
  KEY `journal_entries_kind_index` (`kind`),
  KEY `journal_entries_source_table_index` (`source_table`),
  KEY `journal_entries_source_id_index` (`source_id`),
  KEY `journal_entries_transaction_number_index` (`transaction_number`),
  KEY `journal_entries_branch_id_index` (`branch_id`),
  KEY `journal_entries_reverses_entry_id_index` (`reverses_entry_id`),
  KEY `journal_entries_reversed_by_entry_id_index` (`reversed_by_entry_id`),
  KEY `journal_entries_status_index` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=88 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `journal_lines` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `entry_id` bigint unsigned NOT NULL,
  `line_no` smallint NOT NULL,
  `account_id` bigint unsigned NOT NULL,
  `account_code` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  `account_name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dr` decimal(18,4) NOT NULL DEFAULT '0.0000',
  `cr` decimal(18,4) NOT NULL DEFAULT '0.0000',
  `currency` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `counterparty_type` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `counterparty_id` bigint unsigned DEFAULT NULL,
  `cost_object_type` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cost_object_id` bigint unsigned DEFAULT NULL,
  `branch_id` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `journal_lines_entry_id_line_no_unique` (`entry_id`,`line_no`),
  KEY `journal_lines_entry_id_index` (`entry_id`),
  KEY `journal_lines_account_id_index` (`account_id`),
  KEY `journal_lines_currency_index` (`currency`),
  KEY `journal_lines_counterparty_type_index` (`counterparty_type`),
  KEY `journal_lines_counterparty_id_index` (`counterparty_id`),
  KEY `journal_lines_branch_id_index` (`branch_id`),
  KEY `journal_lines_cost_object_idx` (`cost_object_type`,`cost_object_id`)
) ENGINE=InnoDB AUTO_INCREMENT=181 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `migrations` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=65 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `notifications` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `notifiable_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `notifiable_id` bigint unsigned NOT NULL,
  `data` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `read_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `notifications_notifiable_type_notifiable_id_index` (`notifiable_type`,`notifiable_id`),
  KEY `notifications_unread_idx` (`notifiable_type`,`notifiable_id`,`read_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `owners` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name_en` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `share_percentage` decimal(6,3) NOT NULL DEFAULT '0.000',
  `national_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  `notes` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `password_reset_tokens` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `personal_access_tokens` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tokenable_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenable_id` bigint unsigned NOT NULL,
  `name` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text COLLATE utf8mb4_unicode_ci,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `expires_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`),
  KEY `personal_access_tokens_expires_at_index` (`expires_at`)
) ENGINE=InnoDB AUTO_INCREMENT=631 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `prepayment_applications` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `prepayment_id` bigint unsigned NOT NULL,
  `amount` decimal(18,4) NOT NULL,
  `applied_to_ref` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `applied_to_type` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `applied_to_id` bigint unsigned DEFAULT NULL,
  `notes` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `applied_by_user_id` bigint unsigned DEFAULT NULL,
  `applied_by_user_name` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `applied_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `prepayment_applications_prepayment_id_index` (`prepayment_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `prepayments` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `client_id` bigint unsigned NOT NULL,
  `source_transaction_id` bigint unsigned NOT NULL,
  `currency` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `original_amount` decimal(18,4) NOT NULL,
  `applied_amount` decimal(18,4) NOT NULL DEFAULT '0.0000',
  `remaining_amount` decimal(18,4) NOT NULL,
  `status` enum('open','fully_applied','cancelled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open',
  `received_date` date NOT NULL,
  `created_by_user_id` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `prepayments_source_transaction_id_unique` (`source_transaction_id`),
  KEY `prepayments_client_id_index` (`client_id`),
  KEY `prepayments_status_index` (`status`),
  KEY `prepayments_received_date_index` (`received_date`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `product_catalog` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `unit` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pcs',
  `default_unit_cost` decimal(18,4) NOT NULL DEFAULT '0.0000',
  `default_unit_cost_currency` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'usd',
  `default_unit_price` decimal(18,4) NOT NULL DEFAULT '0.0000',
  `default_weight_kg` decimal(18,4) DEFAULT NULL,
  `default_cbm` decimal(18,4) DEFAULT NULL,
  `photo_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `usage_count` int unsigned NOT NULL DEFAULT '0',
  `last_used_at` timestamp NULL DEFAULT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `product_catalog_is_active_usage_count_index` (`is_active`,`usage_count`),
  KEY `product_catalog_code_index` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `purchase_audit_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `entity_type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `entity_id` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `action` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `old_values` json DEFAULT NULL,
  `new_values` json DEFAULT NULL,
  `changes` json DEFAULT NULL,
  `performed_by_id` bigint unsigned NOT NULL,
  `user_role` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reason` text COLLATE utf8mb4_unicode_ci,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `performed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `purchase_audit_logs_entity_type_entity_id_index` (`entity_type`,`entity_id`),
  KEY `purchase_audit_logs_performed_by_id_performed_at_index` (`performed_by_id`,`performed_at`),
  KEY `purchase_audit_logs_action_performed_at_index` (`action`,`performed_at`),
  CONSTRAINT `purchase_audit_logs_performed_by_id_foreign` FOREIGN KEY (`performed_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `purchase_order_attachments` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `purchase_order_id` bigint unsigned NOT NULL,
  `type` enum('PURCHASE_INVOICE','PRODUCT_IMAGE','RECEIVED_PHOTO','PACKING_PHOTO','TRACKING_SCREENSHOT','EXCHANGE_RATE_PROOF','CUSTOMER_REQUEST','OTHER') COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_path` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `file_size` int unsigned NOT NULL,
  `mime_type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `uploaded_by_id` bigint unsigned NOT NULL,
  `uploaded_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `purchase_order_attachments_uploaded_by_id_foreign` (`uploaded_by_id`),
  KEY `purchase_order_attachments_purchase_order_id_type_index` (`purchase_order_id`,`type`),
  CONSTRAINT `purchase_order_attachments_purchase_order_id_foreign` FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `purchase_order_attachments_uploaded_by_id_foreign` FOREIGN KEY (`uploaded_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `purchase_order_items` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `purchase_order_id` bigint unsigned NOT NULL,
  `product_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `product_name_ar` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `product_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `supplier_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `supplier_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `quantity` int unsigned NOT NULL DEFAULT '1',
  `unit_price` decimal(14,2) NOT NULL,
  `estimated_amount` decimal(14,2) NOT NULL,
  `actual_amount` decimal(14,2) DEFAULT NULL,
  `currency` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL,
  `color` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `size` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `variant` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `specifications` json DEFAULT NULL,
  `weight_kg` decimal(8,3) DEFAULT NULL,
  `length_cm` decimal(8,2) DEFAULT NULL,
  `width_cm` decimal(8,2) DEFAULT NULL,
  `height_cm` decimal(8,2) DEFAULT NULL,
  `volume_m3` decimal(10,6) DEFAULT NULL,
  `item_status` enum('PENDING','PURCHASED','RECEIVED','PARTIALLY_RECEIVED','DAMAGED','WRONG_ITEM','RETURNED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING',
  `received_qty` int unsigned NOT NULL DEFAULT '0',
  `received_at` timestamp NULL DEFAULT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `purchase_order_items_purchase_order_id_item_status_index` (`purchase_order_id`,`item_status`),
  CONSTRAINT `purchase_order_items_purchase_order_id_foreign` FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `purchase_order_status_history` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `purchase_order_id` bigint unsigned NOT NULL,
  `from_status` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `to_status` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `reason` text COLLATE utf8mb4_unicode_ci,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `performed_by_id` bigint unsigned NOT NULL,
  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `changed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `purchase_order_status_history_performed_by_id_foreign` (`performed_by_id`),
  KEY `purchase_order_status_history_purchase_order_id_changed_at_index` (`purchase_order_id`,`changed_at`),
  CONSTRAINT `purchase_order_status_history_performed_by_id_foreign` FOREIGN KEY (`performed_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `purchase_order_status_history_purchase_order_id_foreign` FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `purchase_orders` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `order_number` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `customer_id` int unsigned NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `buyer_id` bigint unsigned DEFAULT NULL,
  `purchase_currency` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL,
  `customer_currency` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL,
  `exchange_rate_id` bigint unsigned DEFAULT NULL,
  `frozen_exchange_rate` decimal(18,8) DEFAULT NULL,
  `exchange_rate_frozen_at` timestamp NULL DEFAULT NULL,
  `estimated_purchase_amount` decimal(14,2) DEFAULT NULL,
  `estimated_total_usd` decimal(14,2) DEFAULT NULL,
  `actual_purchase_amount` decimal(14,2) DEFAULT NULL,
  `actual_total_usd` decimal(14,2) DEFAULT NULL,
  `commission_type` enum('NONE','PERCENTAGE','FIXED_AMOUNT') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PERCENTAGE',
  `commission_value` decimal(10,4) DEFAULT NULL,
  `commission_amount` decimal(12,2) DEFAULT NULL,
  `commission_notes` text COLLATE utf8mb4_unicode_ci,
  `customer_charged_amount` decimal(14,2) DEFAULT NULL,
  `customer_charged_usd` decimal(14,2) DEFAULT NULL,
  `status` enum('PENDING_CONFIRMATION','CONFIRMED','PURCHASING','PURCHASED','RECEIVED_WAREHOUSE','IN_SHIPMENT','DELIVERED','CANCELLED','RETURNED','REFUNDED','ON_HOLD') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING_CONFIRMATION',
  `customer_notes` text COLLATE utf8mb4_unicode_ci,
  `internal_notes` text COLLATE utf8mb4_unicode_ci,
  `contact_source` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shipment_id` bigint unsigned DEFAULT NULL,
  `container_id` bigint unsigned DEFAULT NULL,
  `added_to_shipment_at` timestamp NULL DEFAULT NULL,
  `tracking_number` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `supplier_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `supplier_contact` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `requested_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `confirmed_at` timestamp NULL DEFAULT NULL,
  `purchasing_started_at` timestamp NULL DEFAULT NULL,
  `purchased_at` timestamp NULL DEFAULT NULL,
  `received_at` timestamp NULL DEFAULT NULL,
  `shipped_at` timestamp NULL DEFAULT NULL,
  `delivered_at` timestamp NULL DEFAULT NULL,
  `cancelled_at` timestamp NULL DEFAULT NULL,
  `cancellation_reason` text COLLATE utf8mb4_unicode_ci,
  `cancelled_by_id` bigint unsigned DEFAULT NULL,
  `created_by_id` bigint unsigned NOT NULL,
  `idempotency_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `purchase_orders_order_number_unique` (`order_number`),
  UNIQUE KEY `purchase_orders_idempotency_key_unique` (`idempotency_key`),
  KEY `purchase_orders_exchange_rate_id_foreign` (`exchange_rate_id`),
  KEY `purchase_orders_cancelled_by_id_foreign` (`cancelled_by_id`),
  KEY `purchase_orders_created_by_id_foreign` (`created_by_id`),
  KEY `purchase_orders_customer_id_status_index` (`customer_id`,`status`),
  KEY `purchase_orders_buyer_id_status_index` (`buyer_id`,`status`),
  KEY `purchase_orders_warehouse_id_status_index` (`warehouse_id`,`status`),
  KEY `purchase_orders_status_created_at_index` (`status`,`created_at`),
  KEY `purchase_orders_shipment_id_index` (`shipment_id`),
  KEY `purchase_orders_customer_id_index` (`customer_id`),
  CONSTRAINT `purchase_orders_buyer_id_foreign` FOREIGN KEY (`buyer_id`) REFERENCES `buyers` (`id`) ON DELETE SET NULL,
  CONSTRAINT `purchase_orders_cancelled_by_id_foreign` FOREIGN KEY (`cancelled_by_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `purchase_orders_created_by_id_foreign` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `purchase_orders_exchange_rate_id_foreign` FOREIGN KEY (`exchange_rate_id`) REFERENCES `exchange_rates` (`id`) ON DELETE SET NULL,
  CONSTRAINT `purchase_orders_warehouse_id_foreign` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `receipts` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `series_letter` varchar(4) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'A',
  `series_number` bigint unsigned NOT NULL,
  `source_table` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `source_id` bigint unsigned NOT NULL,
  `transaction_number` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `auto_id` bigint unsigned DEFAULT NULL,
  `kind` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `currency` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amount` decimal(20,4) DEFAULT NULL,
  `counterparty_type` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `counterparty_id` bigint unsigned DEFAULT NULL,
  `counterparty_label` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `counterparty_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `branch_id` bigint unsigned DEFAULT NULL,
  `purpose` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `issued_by_user_id` bigint unsigned DEFAULT NULL,
  `issued_by_user_name` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `issued_at` datetime NOT NULL,
  `voided` tinyint(1) NOT NULL DEFAULT '0',
  `voided_by_user_id` bigint unsigned DEFAULT NULL,
  `voided_at` datetime DEFAULT NULL,
  `void_reason` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `receipts_series_unique` (`series_letter`,`series_number`),
  KEY `receipts_source_table_source_id_index` (`source_table`,`source_id`),
  KEY `receipts_counterparty_type_counterparty_id_index` (`counterparty_type`,`counterparty_id`),
  KEY `receipts_kind_index` (`kind`),
  KEY `receipts_transaction_number_index` (`transaction_number`),
  KEY `receipts_auto_id_index` (`auto_id`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `sessions` (
  `id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` bigint unsigned DEFAULT NULL,
  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent` text COLLATE utf8mb4_unicode_ci,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_activity` int NOT NULL,
  PRIMARY KEY (`id`),
  KEY `sessions_user_id_index` (`user_id`),
  KEY `sessions_last_activity_index` (`last_activity`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `shipment_pieces` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tracking_code` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL,
  `source_table` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `source_id` bigint unsigned NOT NULL,
  `client_id` bigint unsigned DEFAULT NULL,
  `piece_index` smallint unsigned NOT NULL,
  `piece_total` smallint unsigned NOT NULL,
  `status` enum('active','cancelled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `created_by` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `shipment_pieces_src_idx_unique` (`source_table`,`source_id`,`piece_index`),
  UNIQUE KEY `shipment_pieces_tracking_code_unique` (`tracking_code`),
  KEY `shipment_pieces_source_table_index` (`source_table`),
  KEY `shipment_pieces_source_id_index` (`source_id`),
  KEY `shipment_pieces_client_id_index` (`client_id`),
  KEY `shipment_pieces_status_index` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=1078 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `sourcing_deal_health_snapshots` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `sourcing_request_id` bigint unsigned NOT NULL,
  `snapshot_date` date NOT NULL,
  `score` tinyint unsigned NOT NULL,
  `factors` json DEFAULT NULL,
  `computed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `sdhs_proforma_date_uq` (`sourcing_request_id`,`snapshot_date`),
  KEY `sdhs_date_idx` (`snapshot_date`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `sourcing_request_change_requests` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `sourcing_request_id` bigint unsigned NOT NULL,
  `comment` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `suggested_changes` json DEFAULT NULL,
  `reply_to_email` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` enum('pending','responded','dismissed','superseded') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `responded_at` timestamp NULL DEFAULT NULL,
  `responded_by_user_id` bigint unsigned DEFAULT NULL,
  `response` text COLLATE utf8mb4_unicode_ci,
  `share_token_used` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `client_ip` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sourcing_request_change_requests_sourcing_request_id_index` (`sourcing_request_id`),
  KEY `sourcing_request_change_requests_status_index` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `sourcing_request_documents` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `sourcing_request_id` bigint unsigned NOT NULL,
  `path` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `original_name` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mime` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `size_bytes` int unsigned DEFAULT NULL,
  `label` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `visibility` enum('internal','client_visible') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'internal',
  `uploaded_by` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sourcing_request_documents_sourcing_request_id_index` (`sourcing_request_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `sourcing_request_item_photos` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `item_id` bigint unsigned NOT NULL,
  `path` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `original_name` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `size_bytes` int unsigned DEFAULT NULL,
  `mime` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_primary` tinyint(1) NOT NULL DEFAULT '0',
  `caption` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sort_order` smallint unsigned NOT NULL DEFAULT '0',
  `uploaded_by` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sourcing_request_item_photos_item_id_is_primary_index` (`item_id`,`is_primary`),
  KEY `sourcing_request_item_photos_item_id_sort_order_index` (`item_id`,`sort_order`),
  KEY `sourcing_request_item_photos_item_id_index` (`item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `sourcing_request_items` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `sourcing_request_id` bigint unsigned NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `quantity` decimal(18,4) NOT NULL DEFAULT '1.0000',
  `unit` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pcs',
  `unit_cost` decimal(18,4) NOT NULL DEFAULT '0.0000',
  `unit_cost_currency` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'usd',
  `unit_price_to_client` decimal(18,4) NOT NULL DEFAULT '0.0000',
  `weight_kg` decimal(18,4) DEFAULT NULL,
  `cbm` decimal(18,4) DEFAULT NULL,
  `delivery_status` enum('pending','sourced','in_production','shipped','delivered') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `promised_delivery_date` date DEFAULT NULL,
  `supplier_confirmed_date` date DEFAULT NULL,
  `status_changed_at` timestamp NULL DEFAULT NULL,
  `sort_order` smallint unsigned NOT NULL DEFAULT '0',
  `source_quote_id` bigint unsigned DEFAULT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sourcing_request_items_sourcing_request_id_sort_order_index` (`sourcing_request_id`,`sort_order`),
  KEY `sourcing_request_items_sourcing_request_id_index` (`sourcing_request_id`),
  KEY `sourcing_request_items_source_quote_id_index` (`source_quote_id`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `sourcing_request_payments` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `sourcing_request_id` bigint unsigned NOT NULL,
  `sequence` smallint unsigned NOT NULL DEFAULT '1',
  `label` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `percentage` decimal(8,4) NOT NULL DEFAULT '0.0000',
  `amount` decimal(18,4) NOT NULL DEFAULT '0.0000',
  `currency` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `due_date` date DEFAULT NULL,
  `status` enum('scheduled','partial','paid','canceled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'scheduled',
  `paid_amount` decimal(18,4) NOT NULL DEFAULT '0.0000',
  `settled_at` timestamp NULL DEFAULT NULL,
  `settled_by_transaction_id` bigint unsigned DEFAULT NULL,
  `notes` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sourcing_request_payments_sourcing_request_id_sequence_index` (`sourcing_request_id`,`sequence`),
  KEY `sourcing_request_payments_sourcing_request_id_index` (`sourcing_request_id`),
  KEY `sourcing_request_payments_status_index` (`status`),
  KEY `sourcing_request_payments_settled_by_transaction_id_index` (`settled_by_transaction_id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `sourcing_request_purchase_orders` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `sourcing_request_id` bigint unsigned NOT NULL,
  `purchase_order_id` bigint unsigned NOT NULL,
  `note` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `linked_by_user_id` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `sr_po_unique` (`sourcing_request_id`,`purchase_order_id`),
  KEY `sourcing_request_purchase_orders_sourcing_request_id_index` (`sourcing_request_id`),
  KEY `sourcing_request_purchase_orders_purchase_order_id_index` (`purchase_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `sourcing_request_quotes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `sourcing_request_id` bigint unsigned NOT NULL,
  `supplier_id` bigint unsigned DEFAULT NULL,
  `supplier_name_freeform` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unit_price` decimal(18,4) NOT NULL,
  `quantity` decimal(18,4) DEFAULT NULL,
  `total_price` decimal(18,4) NOT NULL,
  `currency` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `lead_time_days` int unsigned DEFAULT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `status` enum('proposed','accepted','rejected') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'proposed',
  `created_by` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sourcing_request_quotes_sourcing_request_id_index` (`sourcing_request_id`),
  KEY `sourcing_request_quotes_supplier_id_index` (`supplier_id`),
  KEY `sourcing_request_quotes_status_index` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `sourcing_request_versions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `sourcing_request_id` bigint unsigned NOT NULL,
  `version_no` int unsigned NOT NULL,
  `trigger` enum('manual','sent','approved','fulfilled','markup_applied','plan_regenerated','cloned_from') COLLATE utf8mb4_unicode_ci NOT NULL,
  `label` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `snapshot_json` json NOT NULL,
  `status_at_snapshot` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `total_at_snapshot` decimal(18,4) NOT NULL DEFAULT '0.0000',
  `currency_at_snapshot` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `item_count_at_snapshot` int unsigned NOT NULL DEFAULT '0',
  `created_by_user_id` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `sourcing_request_versions_sourcing_request_id_version_no_unique` (`sourcing_request_id`,`version_no`),
  KEY `sourcing_request_versions_sourcing_request_id_index` (`sourcing_request_id`),
  KEY `sourcing_request_versions_version_no_index` (`version_no`),
  KEY `sourcing_request_versions_trigger_index` (`trigger`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `sourcing_requests` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `request_number` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `client_id` bigint unsigned NOT NULL,
  `branch_id` bigint unsigned DEFAULT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `target_quantity` decimal(18,4) DEFAULT NULL,
  `target_unit` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `target_unit_price` decimal(18,4) DEFAULT NULL,
  `currency` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `display_currency` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fx_rate_snapshot` json DEFAULT NULL,
  `fx_frozen_on` date DEFAULT NULL,
  `status` enum('open','searching','quoted','accepted','fulfilled','canceled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open',
  `commission_amount` decimal(18,4) DEFAULT NULL,
  `commission_currency` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `commission_posted_at` timestamp NULL DEFAULT NULL,
  `commission_journal_entry_id` bigint unsigned DEFAULT NULL,
  `commission_mode` enum('visible_separate','hidden_in_prices') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'hidden_in_prices',
  `payment_plan` enum('100','50_50','30_50_20','30_30_40','custom') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '100',
  `terms_text` text COLLATE utf8mb4_unicode_ci,
  `items_subtotal` decimal(18,4) NOT NULL DEFAULT '0.0000',
  `proforma_total` decimal(18,4) NOT NULL DEFAULT '0.0000',
  `share_token` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `share_token_expires_at` timestamp NULL DEFAULT NULL,
  `sent_at` timestamp NULL DEFAULT NULL,
  `client_viewed_at` timestamp NULL DEFAULT NULL,
  `client_view_count` int unsigned NOT NULL DEFAULT '0',
  `approved_via` enum('client_portal','on_behalf','admin_direct') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `approved_by_user_id` bigint unsigned DEFAULT NULL,
  `approved_at` timestamp NULL DEFAULT NULL,
  `purchase_order_id` bigint unsigned DEFAULT NULL,
  `freight_kind` enum('sky','sea') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `freight_container_id` bigint unsigned DEFAULT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `sourcing_requests_request_number_unique` (`request_number`),
  UNIQUE KEY `sourcing_requests_share_token_unique` (`share_token`),
  KEY `sourcing_requests_client_id_status_index` (`client_id`,`status`),
  KEY `sourcing_requests_branch_id_status_index` (`branch_id`,`status`),
  KEY `sourcing_requests_client_id_index` (`client_id`),
  KEY `sourcing_requests_branch_id_index` (`branch_id`),
  KEY `sourcing_requests_status_index` (`status`),
  KEY `sourcing_requests_commission_journal_entry_id_index` (`commission_journal_entry_id`),
  KEY `sourcing_requests_purchase_order_id_index` (`purchase_order_id`),
  KEY `sourcing_requests_freight_idx` (`freight_kind`,`freight_container_id`),
  KEY `sourcing_requests_deleted_at_idx` (`deleted_at`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `sticker_batches` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `batch_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `quantity` int unsigned NOT NULL,
  `generated_by_user_id` bigint unsigned NOT NULL,
  `generated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `pdf_path` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `notes` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `sticker_batches_batch_code_unique` (`batch_code`),
  KEY `sticker_batches_generated_by_user_id_foreign` (`generated_by_user_id`),
  CONSTRAINT `sticker_batches_generated_by_user_id_foreign` FOREIGN KEY (`generated_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=549 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `stickers` (
  `id` char(26) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch_id` bigint unsigned NOT NULL,
  `shipment_piece_id` bigint unsigned DEFAULT NULL,
  `printed_at` timestamp NULL DEFAULT NULL,
  `assigned_at` timestamp NULL DEFAULT NULL,
  `revoked_at` timestamp NULL DEFAULT NULL,
  `revoke_reason` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `stickers_shipment_piece_id_index` (`shipment_piece_id`),
  KEY `stickers_batch_id_assigned_at_index` (`batch_id`,`assigned_at`),
  CONSTRAINT `stickers_batch_id_foreign` FOREIGN KEY (`batch_id`) REFERENCES `sticker_batches` (`id`) ON DELETE CASCADE,
  CONSTRAINT `stickers_shipment_piece_id_foreign` FOREIGN KEY (`shipment_piece_id`) REFERENCES `shipment_pieces` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `store_out_sea` (
  `id` int NOT NULL AUTO_INCREMENT,
  `in_id` text COLLATE utf8mb4_general_ci,
  `client_id` text COLLATE utf8mb4_general_ci,
  `client_code` text COLLATE utf8mb4_general_ci,
  `number` text COLLATE utf8mb4_general_ci,
  `cbm` text COLLATE utf8mb4_general_ci,
  `kg` text COLLATE utf8mb4_general_ci,
  `unit` text COLLATE utf8mb4_general_ci,
  `price` text COLLATE utf8mb4_general_ci,
  `plus` text COLLATE utf8mb4_general_ci,
  `currency` text COLLATE utf8mb4_general_ci,
  `created_date` date DEFAULT NULL,
  `created_time` text COLLATE utf8mb4_general_ci,
  `created_by` text COLLATE utf8mb4_general_ci,
  `transaction_number` text COLLATE utf8mb4_general_ci,
  `container_id` text COLLATE utf8mb4_general_ci,
  `new_price` text COLLATE utf8mb4_general_ci,
  `payment` text COLLATE utf8mb4_general_ci,
  `payment_pending` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `branch` text COLLATE utf8mb4_general_ci,
  `images` text COLLATE utf8mb4_general_ci,
  `exchange_rate` text COLLATE utf8mb4_general_ci,
  `canceled` text COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=185 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `store_out_sky` (
  `id` int NOT NULL AUTO_INCREMENT,
  `in_id` text COLLATE utf8mb4_general_ci,
  `client_id` text COLLATE utf8mb4_general_ci,
  `client_code` text COLLATE utf8mb4_general_ci,
  `number` text COLLATE utf8mb4_general_ci,
  `cbm` text COLLATE utf8mb4_general_ci,
  `kg` text COLLATE utf8mb4_general_ci,
  `unit` text COLLATE utf8mb4_general_ci,
  `price` text COLLATE utf8mb4_general_ci,
  `plus` text COLLATE utf8mb4_general_ci,
  `currency` text COLLATE utf8mb4_general_ci,
  `created_date` date DEFAULT NULL,
  `created_time` text COLLATE utf8mb4_general_ci,
  `created_by` text COLLATE utf8mb4_general_ci,
  `transaction_number` text COLLATE utf8mb4_general_ci,
  `container_id` text COLLATE utf8mb4_general_ci,
  `new_price` text COLLATE utf8mb4_general_ci,
  `payment` text COLLATE utf8mb4_general_ci,
  `payment_pending` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `branch` text COLLATE utf8mb4_general_ci,
  `images` text COLLATE utf8mb4_general_ci,
  `exchange_rate` text COLLATE utf8mb4_general_ci,
  `canceled` text COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `store_sea` (
  `id` int NOT NULL AUTO_INCREMENT,
  `out_id` text COLLATE utf8mb4_general_ci,
  `client_id` text COLLATE utf8mb4_general_ci,
  `client_code` text COLLATE utf8mb4_general_ci,
  `company_name` text COLLATE utf8mb4_general_ci,
  `ship_from` text COLLATE utf8mb4_general_ci,
  `type` text COLLATE utf8mb4_general_ci,
  `number` text COLLATE utf8mb4_general_ci,
  `category` text COLLATE utf8mb4_general_ci,
  `cbm` text COLLATE utf8mb4_general_ci,
  `kg` text COLLATE utf8mb4_general_ci,
  `receipt` text COLLATE utf8mb4_general_ci,
  `brand` text COLLATE utf8mb4_general_ci,
  `images` text COLLATE utf8mb4_general_ci,
  `notes` text COLLATE utf8mb4_general_ci,
  `created_date` date DEFAULT NULL,
  `created_time` text COLLATE utf8mb4_general_ci,
  `created_by` text COLLATE utf8mb4_general_ci,
  `canceled` text COLLATE utf8mb4_general_ci,
  `canceled_by` text COLLATE utf8mb4_general_ci,
  `canceled_date` text COLLATE utf8mb4_general_ci,
  `canceled_time` text COLLATE utf8mb4_general_ci,
  `transaction_number` text COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `store_sky` (
  `id` int NOT NULL AUTO_INCREMENT,
  `out_id` text COLLATE utf8mb4_general_ci,
  `client_id` text COLLATE utf8mb4_general_ci,
  `client_code` text COLLATE utf8mb4_general_ci,
  `company_name` text COLLATE utf8mb4_general_ci,
  `ship_from` text COLLATE utf8mb4_general_ci,
  `type` text COLLATE utf8mb4_general_ci,
  `number` text COLLATE utf8mb4_general_ci,
  `category` text COLLATE utf8mb4_general_ci,
  `cbm` text COLLATE utf8mb4_general_ci,
  `kg` text COLLATE utf8mb4_general_ci,
  `receipt` text COLLATE utf8mb4_general_ci,
  `brand` text COLLATE utf8mb4_general_ci,
  `images` text COLLATE utf8mb4_general_ci,
  `notes` text COLLATE utf8mb4_general_ci,
  `created_date` date DEFAULT NULL,
  `created_time` text COLLATE utf8mb4_general_ci,
  `created_by` text COLLATE utf8mb4_general_ci,
  `canceled` text COLLATE utf8mb4_general_ci,
  `canceled_by` text COLLATE utf8mb4_general_ci,
  `canceled_date` text COLLATE utf8mb4_general_ci,
  `canceled_time` text COLLATE utf8mb4_general_ci,
  `transaction_number` text COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `suppliers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` text COLLATE utf8mb4_general_ci,
  `balance_usd` text COLLATE utf8mb4_general_ci,
  `balance_den` text COLLATE utf8mb4_general_ci,
  `balance_eur` text COLLATE utf8mb4_general_ci,
  `balance_cny` text COLLATE utf8mb4_general_ci,
  `created_date` date DEFAULT NULL,
  `created_time` text COLLATE utf8mb4_general_ci,
  `deleted` text COLLATE utf8mb4_general_ci,
  `created_by` text COLLATE utf8mb4_general_ci,
  `not_active` text COLLATE utf8mb4_general_ci,
  `sky_sea` text COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `suppliers_transactions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `supplier_id` text COLLATE utf8mb4_general_ci,
  `auto_id` text COLLATE utf8mb4_general_ci,
  `container_id` text COLLATE utf8mb4_general_ci,
  `container_number` text COLLATE utf8mb4_general_ci,
  `sky_sea` text COLLATE utf8mb4_general_ci,
  `branch` text COLLATE utf8mb4_general_ci,
  `value` text COLLATE utf8mb4_general_ci,
  `currency` text COLLATE utf8mb4_general_ci,
  `from_currency` text COLLATE utf8mb4_general_ci,
  `from_value` text COLLATE utf8mb4_general_ci,
  `exchange_rate` text COLLATE utf8mb4_general_ci,
  `type` text COLLATE utf8mb4_general_ci,
  `plus_minus` text COLLATE utf8mb4_general_ci,
  `created_date` date DEFAULT NULL,
  `created_time` text COLLATE utf8mb4_general_ci,
  `created_by` text COLLATE utf8mb4_general_ci,
  `transaction_number` text COLLATE utf8mb4_general_ci,
  `notes` text COLLATE utf8mb4_general_ci,
  `purpose` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=69 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `tracking_branches` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name_en` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `role` enum('HUB','SPOKE','ADMIN') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'SPOKE',
  `country` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'LY',
  `city` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `address` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `latitude` decimal(10,6) DEFAULT NULL,
  `longitude` decimal(10,6) DEFAULT NULL,
  `phone` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tracking_branches_code_unique` (`code`),
  KEY `tracking_branches_role_index` (`role`),
  KEY `tracking_branches_is_active_index` (`is_active`)
) ENGINE=InnoDB AUTO_INCREMENT=1276 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `tracking_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `shipment_source_table` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `shipment_source_id` bigint unsigned NOT NULL,
  `shipment_piece_id` bigint unsigned DEFAULT NULL,
  `kind` enum('INTERNATIONAL','INTERNAL') COLLATE utf8mb4_unicode_ci NOT NULL,
  `event_type` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `occurred_at` timestamp NOT NULL,
  `city` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `country` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `branch_id` bigint unsigned DEFAULT NULL,
  `raw_payload` json DEFAULT NULL,
  `translation_key` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `translation_params` json DEFAULT NULL,
  `recorded_by_user_id` bigint unsigned DEFAULT NULL,
  `client_event_id` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_customer_visible` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tracking_events_kind_client_event_unique` (`kind`,`client_event_id`),
  KEY `tracking_events_shipment_piece_id_foreign` (`shipment_piece_id`),
  KEY `tracking_events_branch_id_foreign` (`branch_id`),
  KEY `tracking_events_recorded_by_user_id_foreign` (`recorded_by_user_id`),
  KEY `tracking_events_shipment_occurred_idx` (`shipment_source_table`,`shipment_source_id`,`occurred_at`),
  KEY `tracking_events_kind_event_type_index` (`kind`,`event_type`),
  KEY `tracking_events_kind_index` (`kind`),
  KEY `tracking_events_occurred_at_index` (`occurred_at`),
  KEY `tracking_events_is_customer_visible_index` (`is_customer_visible`),
  CONSTRAINT `tracking_events_branch_id_foreign` FOREIGN KEY (`branch_id`) REFERENCES `tracking_branches` (`id`) ON DELETE SET NULL,
  CONSTRAINT `tracking_events_recorded_by_user_id_foreign` FOREIGN KEY (`recorded_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `tracking_events_shipment_piece_id_foreign` FOREIGN KEY (`shipment_piece_id`) REFERENCES `shipment_pieces` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=1192 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `treasury_transactions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` text COLLATE utf8mb4_general_ci,
  `type` text COLLATE utf8mb4_general_ci,
  `data` text COLLATE utf8mb4_general_ci,
  `created_date` date DEFAULT NULL,
  `created_time` text COLLATE utf8mb4_general_ci,
  `created_by` text COLLATE utf8mb4_general_ci,
  `value` text COLLATE utf8mb4_general_ci,
  `currency` text COLLATE utf8mb4_general_ci,
  `plus_minus` text COLLATE utf8mb4_general_ci,
  `branch` text COLLATE utf8mb4_general_ci,
  `notes` text COLLATE utf8mb4_general_ci,
  `auto_id` text COLLATE utf8mb4_general_ci,
  `transaction_number` text COLLATE utf8mb4_general_ci,
  `commission` text COLLATE utf8mb4_general_ci,
  `remaining_balance` text COLLATE utf8mb4_general_ci,
  `usd_value` text COLLATE utf8mb4_general_ci,
  `exchange_rate` text COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=799 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `code` text COLLATE utf8mb4_unicode_ci,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` text COLLATE utf8mb4_unicode_ci,
  `branch` text COLLATE utf8mb4_unicode_ci,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `two_factor_secret` text COLLATE utf8mb4_unicode_ci,
  `two_factor_confirmed_at` timestamp NULL DEFAULT NULL,
  `lang` text COLLATE utf8mb4_unicode_ci,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `created_date` text COLLATE utf8mb4_unicode_ci,
  `created_time` text COLLATE utf8mb4_unicode_ci,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted` text COLLATE utf8mb4_unicode_ci,
  `updated_exchange` text COLLATE utf8mb4_unicode_ci,
  `not_active` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=1395 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `warehouses` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name_en` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `country` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `city` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `address` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `local_currency` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `manager_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `warehouses_code_unique` (`code`),
  KEY `warehouses_country_is_active_index` (`country`,`is_active`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `webhook_deliveries` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `provider` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `external_event_id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `event_type` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payload` json NOT NULL,
  `signature` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signature_verified` tinyint(1) NOT NULL DEFAULT '0',
  `received_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `processed_at` timestamp NULL DEFAULT NULL,
  `processing_error` text COLLATE utf8mb4_unicode_ci,
  `attempt_count` tinyint unsigned NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `webhook_deliveries_provider_event_unique` (`provider`,`external_event_id`),
  KEY `webhook_deliveries_provider_processed_at_index` (`provider`,`processed_at`),
  KEY `webhook_deliveries_provider_index` (`provider`),
  KEY `webhook_deliveries_event_type_index` (`event_type`)
) ENGINE=InnoDB AUTO_INCREMENT=388 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



-- migrations table data


INSERT INTO `migrations` VALUES (1,'0001_01_01_000000_create_users_table',1),(2,'0001_01_01_000001_create_cache_table',1),(3,'0001_01_01_000002_create_jobs_table',1),(4,'2025_07_24_083659_create_personal_access_tokens_table',1),(5,'2026_05_13_120000_drop_pass_txt_columns',2),(6,'2026_05_13_130000_create_audit_log_table',2),(7,'2026_05_13_140000_add_purpose_to_clients_transactions',2),(8,'2026_05_13_150000_add_purpose_to_other_transactions',2),(9,'2026_05_14_120000_add_calc_to_clients_transactions',3),(10,'2026_05_15_120000_create_receipts_table',4),(11,'2026_05_15_130000_create_chart_of_accounts_table',5),(12,'2026_05_15_140000_create_fx_rate_history_table',5),(13,'2026_05_15_150000_create_accounting_periods_table',5),(14,'2026_05_15_160000_create_cash_counts_table',5),(15,'2026_05_15_170000_create_prepayments_table',5),(16,'2026_05_15_180000_create_owners_table',5),(17,'2026_05_15_200000_create_journal_entries_table',6),(18,'2026_05_16_120000_create_shipment_pieces_table',7),(19,'2026_05_16_130000_add_payment_pending_to_store_out_tables',8),(20,'2026_05_20_120000_create_client_devices_table',9),(21,'2026_05_20_130000_create_notifications_table',9),(22,'2026_05_20_140000_add_notify_prefs_to_clients_table',10),(23,'2026_05_21_000001_create_warehouses_table',11),(24,'2026_05_21_000002_create_buyers_table',11),(25,'2026_05_21_000003_create_buyer_accounts_table',11),(26,'2026_05_21_000004_create_exchange_rate_configs_table',11),(27,'2026_05_21_000005_create_exchange_rates_table',11),(28,'2026_05_21_000006_create_purchase_orders_table',12),(29,'2026_05_21_000007_create_purchase_order_items_table',12),(30,'2026_05_21_000008_create_buyer_transactions_table',12),(31,'2026_05_21_000009_create_buyer_reconciliations_table',12),(32,'2026_05_21_000010_create_purchase_order_status_history_table',12),(33,'2026_05_21_000011_create_purchase_order_attachments_table',12),(34,'2026_05_21_000014_create_purchase_audit_logs_table',12),(35,'2026_05_22_120001_create_branches_table',13),(36,'2026_05_22_120002_create_branch_staff_table',13),(37,'2026_05_22_120003_create_tracking_events_table',13),(38,'2026_05_22_120004_create_custody_events_table',13),(39,'2026_05_22_120005_create_sticker_batches_table',13),(40,'2026_05_22_120006_create_stickers_table',13),(41,'2026_05_22_120007_create_webhook_deliveries_table',13),(42,'2026_05_22_120008_create_employee_action_logs_table',13),(43,'2026_05_22_120009_create_employee_devices_table',13),(44,'2026_05_22_120010_create_tracking_idempotency_keys_table',13),(45,'2026_05_22_180000_drop_unused_tracking_idempotency_keys_table',14),(46,'2026_05_26_120000_expand_chart_of_accounts',15),(47,'2026_05_26_120100_fix_coa_collisions',16),(48,'2026_05_26_130000_create_sourcing_requests_tables',17),(49,'2026_05_26_140000_add_cost_object_to_journal_lines',18),(50,'2026_05_26_150000_add_commission_reason_to_clients_transactions',19),(51,'2026_05_26_160000_extend_sourcing_requests_for_proforma',20),(52,'2026_05_26_160100_create_sourcing_request_items_tables',20),(53,'2026_05_28_120000_add_freight_link_to_sourcing_requests',21),(54,'2026_05_29_120000_add_client_view_tracking_to_sourcing_requests',22),(55,'2026_05_29_130000_add_status_to_sourcing_request_items',23),(56,'2026_05_29_140000_create_sourcing_request_documents',24),(57,'2026_05_29_150000_create_sourcing_request_change_requests',25),(58,'2026_05_29_160000_add_soft_delete_to_sourcing_requests',26),(59,'2026_05_29_170000_add_portal_token_to_clients',27),(60,'2026_05_29_180000_create_product_catalog',28),(61,'2026_05_29_190000_create_sourcing_request_purchase_orders',29),(62,'2026_05_30_120000_create_sourcing_request_versions',30),(63,'2026_06_05_120000_create_sourcing_deal_health_snapshots',31),(64,'2026_06_07_144808_add_two_factor_to_users_table',32);



-- chart_of_accounts seed data


INSERT INTO `chart_of_accounts` VALUES (1,'1000','Cash on hand','Cash on hand','现金','asset','debit',NULL,1,1,'cash_total','2026-05-15 03:43:40','2026-05-15 03:43:40'),(2,'1010','Bank','Bank','银行','asset','debit',NULL,1,1,NULL,'2026-05-15 03:43:40','2026-05-15 03:43:40'),(3,'1100','Accounts receivable - clients','Accounts receivable - clients','客户应收款','asset','debit',NULL,1,1,'ar_clients','2026-05-15 03:43:40','2026-05-15 03:43:40'),(4,'1200','Prepaid to suppliers','Prepaid to suppliers','供应商预付款','asset','debit',NULL,1,1,'ar_suppliers','2026-05-15 03:43:40','2026-05-15 03:43:40'),(5,'1300','Prepaid to customs brokers','Prepaid to customs brokers','报关行预付款','asset','debit',NULL,1,1,'ar_brokers','2026-05-15 03:43:40','2026-05-15 03:43:40'),(6,'2000','Client deposits (unearned)','Client deposits','客户存款','liability','credit',NULL,1,1,'client_deposits','2026-05-15 03:43:40','2026-05-15 03:43:40'),(7,'2100','Accounts payable - suppliers','Accounts payable - suppliers','供应商应付款','liability','credit',NULL,1,1,'ap_suppliers','2026-05-15 03:43:40','2026-05-15 03:43:40'),(8,'2200','Accounts payable - customs brokers','Accounts payable - customs brokers','报关行应付款','liability','credit',NULL,1,1,'ap_brokers','2026-05-15 03:43:40','2026-05-15 03:43:40'),(9,'3000','Owner\'s equity','Owner\'s equity','所有者权益','equity','credit',NULL,1,1,'owners_equity','2026-05-15 03:43:40','2026-05-15 03:43:40'),(10,'3100','Owner\'s drawings','Owner\'s drawings','所有者提款','equity','debit',NULL,1,1,'owner_drawings','2026-05-15 03:43:40','2026-05-15 03:43:40'),(11,'4000','Commission revenue','Commission revenue','佣金收入','revenue','credit',NULL,1,1,'commission_revenue','2026-05-15 03:43:40','2026-05-15 03:43:40'),(12,'4100','Shipping revenue','Shipping revenue','运输收入','revenue','credit',NULL,1,1,'shipping_revenue','2026-05-15 03:43:40','2026-05-15 03:43:40'),(13,'5000','Operating expenses','Operating expenses','运营费用','expense','debit',NULL,1,1,'operating_expenses','2026-05-15 03:43:40','2026-05-15 03:43:40'),(14,'5100','Owner\'s salary','Owner\'s salary','所有者工资','expense','debit',NULL,1,1,'owner_salary','2026-05-15 03:43:40','2026-05-15 03:43:40'),(15,'5200','FX gain/loss','FX gain/loss','汇兑损益','expense','debit',NULL,1,1,NULL,'2026-05-15 03:43:40','2026-05-15 03:43:40'),(16,'1250','عُهدة المشتريات (USD)','Buyer custody (USD)','采购托管','asset','debit',NULL,1,1,'buyer_custody','2026-05-21 06:43:54','2026-05-21 06:43:54'),(17,'1320','مشتريات تحت التسليم','Purchases in transit','在途采购','asset','debit',NULL,1,1,'purchases_in_transit','2026-05-21 06:43:54','2026-05-21 06:43:54'),(18,'1400','بضاعة في المستودع','Warehouse inventory','仓库存货','asset','debit',NULL,1,1,'warehouse_inventory','2026-05-21 06:43:54','2026-05-21 06:43:54'),(19,'1500','بضاعة في الشحن','Goods in shipment','在运货物','asset','debit',NULL,1,1,'goods_in_shipment','2026-05-21 06:43:54','2026-05-21 06:43:54'),(20,'4200','أرباح فروقات الصرف','FX gain','汇兑收益','revenue','credit',NULL,1,1,'fx_gain','2026-05-21 06:43:54','2026-05-21 06:43:54'),(21,'5400','تكلفة البضاعة المسلَّمة','COGS — delivered','已交付商品成本','expense','debit',NULL,1,1,'cogs_delivered','2026-05-21 06:43:54','2026-05-21 06:43:54'),(22,'1600','Prepaid expenses','Prepaid expenses','预付费用','asset','debit',NULL,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(23,'2300','Accounts payable - carriers','Accounts payable - carriers','承运商应付款','liability','credit',NULL,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(24,'2400','Accrued expenses','Accrued expenses','应计费用','liability','credit',NULL,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(25,'3200','Partners\' current accounts','Partners\' current accounts','合伙人往来','equity','credit',NULL,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(26,'3300','Partners\' drawings','Partners\' drawings','合伙人提款','equity','debit',NULL,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(27,'4010','Purchase commission revenue','Purchase commission revenue','采购佣金收入','revenue','credit',11,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(28,'4020','Sourcing commission revenue','Sourcing commission revenue','寻货佣金收入','revenue','credit',11,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(29,'4110','Air freight revenue','Air freight revenue','空运收入','revenue','credit',12,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(30,'4120','LCL sea freight revenue','LCL sea freight revenue','海运拼箱收入','revenue','credit',12,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(31,'4130','FCL container revenue','FCL container revenue','海运整箱收入','revenue','credit',12,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(32,'4300','Packaging revenue','Packaging revenue','包装收入','revenue','credit',NULL,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(34,'5300','Salaries','Salaries','工资','expense','debit',NULL,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(35,'5310','Rent','Rent','租金','expense','debit',NULL,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(36,'5320','Domestic freight','Domestic freight','国内运费','expense','debit',NULL,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(37,'5330','Customs clearance expense','Customs clearance expense','报关费','expense','debit',NULL,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(38,'5340','Loading and unloading','Loading and unloading','装卸费','expense','debit',NULL,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(39,'5350','Inter-city transport','Inter-city transport','城际运输','expense','debit',NULL,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(40,'5360','Port fees','Port fees','港口费','expense','debit',NULL,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(41,'5370','Warehouse fees','Warehouse fees','仓储费','expense','debit',NULL,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(42,'5380','Marketing and advertising','Marketing and advertising','市场营销','expense','debit',NULL,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(43,'5390','Wire transfer fees','Wire transfer fees','汇款手续费','expense','debit',NULL,1,1,NULL,'2026-05-26 02:41:51','2026-05-26 02:41:51'),(44,'1410','Employee custody','Employee custody','员工备用金','asset','debit',NULL,1,1,NULL,'2026-05-26 02:44:56','2026-05-26 02:44:56'),(45,'4210','Inspection revenue','Inspection revenue','验货收入','revenue','credit',NULL,1,1,NULL,'2026-05-26 02:44:56','2026-05-26 02:44:56'),(46,'5410','Administrative expenses','Administrative expenses','管理费用','expense','debit',NULL,1,1,NULL,'2026-05-26 02:44:56','2026-05-26 02:44:56');



-- tracking_branches seed data


INSERT INTO `tracking_branches` VALUES (298,'TRIPOLI_HUB','طرابلس - المركز الرئيسي','Tripoli HQ','HUB','LY','Tripoli',NULL,NULL,NULL,NULL,1,'2026-05-22 13:56:34','2026-05-22 13:57:34'),(299,'MISRATA_HUB','مصراتة - المستودع','Misrata Hub','HUB','LY','Misrata',NULL,NULL,NULL,NULL,1,'2026-05-22 13:56:34','2026-05-22 13:57:34'),(300,'BENGHAZI_HUB','بنغازي - المستودع','Benghazi Hub','HUB','LY','Benghazi',NULL,NULL,NULL,NULL,1,'2026-05-22 13:56:34','2026-05-22 13:57:34'),(301,'TRIPOLI_TAJOURA','طرابلس - تاجوراء','Tripoli - Tajoura','SPOKE','LY','Tripoli',NULL,NULL,NULL,NULL,1,'2026-05-22 13:56:34','2026-05-22 13:57:34'),(302,'TRIPOLI_JANZUR','طرابلس - جنزور','Tripoli - Janzur','SPOKE','LY','Tripoli',NULL,NULL,NULL,NULL,1,'2026-05-22 13:56:34','2026-05-22 13:57:34'),(303,'ZAWIYA','الزاوية','Zawiya','SPOKE','LY','Zawiya',NULL,NULL,NULL,NULL,1,'2026-05-22 13:56:34','2026-05-22 13:57:34'),(304,'ZUWARA','زوارة','Zuwara','SPOKE','LY','Zuwara',NULL,NULL,NULL,NULL,1,'2026-05-22 13:56:34','2026-05-22 13:57:34'),(305,'GHARYAN','غريان','Gharyan','SPOKE','LY','Gharyan',NULL,NULL,NULL,NULL,1,'2026-05-22 13:56:34','2026-05-22 13:57:34'),(306,'SIRTE','سرت','Sirte','SPOKE','LY','Sirte',NULL,NULL,NULL,NULL,1,'2026-05-22 13:56:34','2026-05-22 13:57:34'),(307,'KHOMS','الخمس','Khoms','SPOKE','LY','Khoms',NULL,NULL,NULL,NULL,1,'2026-05-22 13:56:34','2026-05-22 13:57:34'),(308,'ZLITEN','زليتن','Zliten','SPOKE','LY','Zliten',NULL,NULL,NULL,NULL,1,'2026-05-22 13:56:34','2026-05-22 13:57:34'),(309,'BANI_WALID','بني وليد','Bani Walid','SPOKE','LY','Bani Walid',NULL,NULL,NULL,NULL,1,'2026-05-22 13:56:34','2026-05-22 13:57:34'),(310,'AJDABIYA','أجدابيا','Ajdabiya','SPOKE','LY','Ajdabiya',NULL,NULL,NULL,NULL,1,'2026-05-22 13:56:34','2026-05-22 13:57:34'),(311,'TOBRUK','طبرق','Tobruk','SPOKE','LY','Tobruk',NULL,NULL,NULL,NULL,1,'2026-05-22 13:56:34','2026-05-22 13:57:34'),(312,'AL_BAYDA','البيضاء','Al Bayda','SPOKE','LY','Al Bayda',NULL,NULL,NULL,NULL,1,'2026-05-22 13:56:34','2026-05-22 13:57:34'),(313,'DERNA','درنة','Derna','SPOKE','LY','Derna',NULL,NULL,NULL,NULL,1,'2026-05-22 13:56:34','2026-05-22 13:57:34'),(314,'SEBHA','سبها','Sebha','SPOKE','LY','Sebha',NULL,NULL,NULL,NULL,1,'2026-05-22 13:56:34','2026-05-22 13:57:34');


